steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/loopedin-app:${_VERSION}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/loopedin-app:${_VERSION}']

- name: 'gcr.io/cloud-builders/kubectl'
  args: 
    - 'set'
    - 'image'
    - 'deployment/loopedin-app-deployment'
    - 'loopedin-image=gcr.io/$PROJECT_ID/loopedin-app:${_VERSION}'
  env:
    - CLOUDSDK_COMPUTE_ZONE=us-central1-c
    - CLOUDSDK_CONTAINER_CLUSTER=looped-in-1

substitutions:
    _VERSION: v6

options:
    substitution_option: 'ALLOW_LOOSE'