version: '3'

services:
  app:
    container_name: looped-in
    build: 
      context: .
      dockerfile: local.Dockerfile
    ports:
      - '3000:3000'
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'