apiVersion: v1
kind: ReplicationController
metadata:
    name: looped-in-rc-3
spec:
    replicas: 3
    selector:
        name: looped-in-3
        version: v1
    template:
        metadata:
            labels:
                name: looped-in-3
                version:  v1
        spec:
            containers:
                - name: db
                  image: mongo
                  ports:
                    - containerPort: 27017
                - name: backend
                  image: gcr.io/looped-in-274723/looped-in-backend
                  ports:
                    - containerPort: 3000
                - name: frontend
                  image: gcr.io/looped-in-274723/front-end-v1
                  ports:
                    - containerPort: 8080